{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-connector.fullname" . }}-api
  labels:
    {{- include "fhir-connector.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "fhir-connector.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
