apiVersion: batch/v1
kind: CronJob
metadata:
  name: fhir-connector
spec:
  schedule: "0 2 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fhir-connector
            env:
            - name: EPI_REPO_BRANCH
              value: "master"
            - name: IPS_REPO_BRANCH
              value: "master"
            - name: EPI_SERVER
              value: "https://gravitate-health.lst.tfo.upm.es/epi/api/fhir"
            - name: IPS_SERVER
              value: "https://gravitate-health.lst.tfo.upm.es/ips/api/fhir"
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 4
