apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:

- path: fhir-connector-api-deployment.yaml
- path: fhir-connector-fhir-sync-hl7-cronjob.yaml
- path: fhir-connector-git-epi-cronjob.yaml
- path: fhir-connector-git-ips-cronjob.yaml
- path: fhir-connector-expugne-epi.yaml
- path: fhir-connector-expugne-ips.yaml
- path: fhir-connector-sm-tool.yaml
