apiVersion: batch/v1
kind: CronJob
metadata:
  name: fhir-connector-git-ips
  labels:
    eu.gravitate-health.fosps.connector: "true"
spec:
  schedule: "0 2 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: fhir-connector-git-ips
            image: gravitate-registry.cr.de-fra.ionos.com/fhir-connector:latest
            env:
            - name: CONNECTOR_MODE
              value: "GIT_FSH"
            - name: MODE_GIT_FSH_SOURCE_REPO
              value: "https://github.com/hl7-eu/gravitate-health-ips.git"
            - name: MODE_GIT_FSH_SOURCE_REPO_BRANCH
              value: "master"
            - name: DESTINATION_SERVER
              value: "https://fosps.gravitatehealth.eu/ips/api/fhir"
            - name: IPS_WHITELIST
              value: |
                - "Bundle-gravitate-Alicia.json"
                - "Bundle-gravitate-Pedro.json"
            - name: LOG_LEVEL
              value: INFO

              # Email settings
            - name: EMAIL_ENABLED
              value: "true"
            - name: EMAIL_SENDER
              value: "fosps-noreply@lst.tfo.upm.es"
            - name: EMAIL_SMTP_SERVER
              value: "smtp.lst.tfo.upm.es"
            - name: EMAIL_RECIPIENT
              value: "fosps-logs@lst.tfo.upm.es"
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fhir-connector-email-password
                  key: password
            imagePullPolicy: Always
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
