apiVersion: batch/v1
kind: CronJob
metadata:
  name: fhir-connector
spec:
  schedule: "0 2 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fhir-connector
              image: gravitate-registry.cr.de-fra.ionos.com/fhir-connector:latest
              envFrom:
                - configMapRef:
                    name: fhir-connector-config-map
              imagePullPolicy: Always
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
