apiVersion: batch/v1
kind: CronJob
metadata:
  name: fhir-connector
spec:
  schedule: "0 2 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: fhir-connector
              image: gravitate-registry.cr.de-fra.ionos.com/fhir-connector:latest
              env:
                - name: EMAIL_ENABLED
                  value: "true"
                - name: EMAIL_SENDER
                  value: fosps-noreply@lst.tfo.upm.es
                - name: EMAIL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: fhir-connector-email-password
                      key: password
                - name: EMAIL_SMTP_SERVER
                  value: smtp.lst.tfo.upm.es
                - name: EMAIL_RECIPIENT
                  value: fosps-logs@lst.tfo.upm.es
              envFrom:
                - configMapRef:
                    name: fhir-connector-config-map
              imagePullPolicy: Always
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
