name: CI CD

on:
  push:
    branches:
      - main

concurrency: production

jobs:
  semantic-versioning-dry-run:
    runs-on: ubuntu-latest
    steps:
    - 
      id: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - 
      name: Minor version for each merge
      id: taggerDryRun
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
    - 
      name: Print tags
      run: |
        echo "New tag is: ${{ steps.taggerDryRun.outputs.new_tag }}"
        echo "Current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
        echo "Increment type is: ${{ steps.taggerDryRun.outputs.part }}"
    outputs:
      new-tag: ${{steps.taggerDryRun.outputs.new_tag}}
      current-tag: ${{steps.taggerDryRun.outputs.tag}}
      increment-type: ${{steps.taggerDryRun.outputs.part}}

  build-and-push:
    needs: semantic-versioning-dry-run
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GH registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.REGISTRY_URL}}/fhir-connector:latest , ${{secrets.REGISTRY_URL}}/fhir-connector:${{ needs.semantic-versioning-dry-run.outputs.new-tag }}
      
  semantic-versioning:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - 
        name: Minor version for each merge
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true